/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { Task } from "./task";

export interface AllTasksResponse {
	pluginTasks: Task[];
	systemTasks: Task[];
}
