/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { ArtistTracksItem } from "./artistTracksItem";
import type { AttributeMap } from "./attributeMap";
import type { Identity } from "./identity";

export interface Artist {
	uuid: string;
	attributes: AttributeMap | null;
	/** @nullable */
	identities: Identity[] | null;
	/** @nullable */
	tracks: ArtistTracksItem[] | null;
}
