/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { BooleanAttribute } from "./booleanAttribute";
import type { BufferAttribute } from "./bufferAttribute";
import type { DecimalAttribute } from "./decimalAttribute";
import type { IntegerAttribute } from "./integerAttribute";
import type { StringAttribute } from "./stringAttribute";

export interface AttributeMap {
	[key: string]:
		| StringAttribute
		| BooleanAttribute
		| IntegerAttribute
		| DecimalAttribute
		| BufferAttribute;
}
