/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */

export type BooleanAttributeType =
	(typeof BooleanAttributeType)[keyof typeof BooleanAttributeType];

export const BooleanAttributeType = {
	boolean: "boolean",
} as const;
