/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { BooleanAttributeType } from "./booleanAttributeType";

export interface BooleanAttribute {
	type: BooleanAttributeType;
	pluginId: string;
	sourceId: string;
	values: boolean[];
}
