/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { BufferAttributeType } from "./bufferAttributeType";
import type { Resource } from "./resource";

export interface BufferAttribute {
	type: BufferAttributeType;
	pluginId: string;
	sourceId: string;
	values: Resource[];
}
