/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { DecimalAttributeType } from "./decimalAttributeType";

export interface DecimalAttribute {
	type: DecimalAttributeType;
	pluginId: string;
	sourceId: string;
	values: number[];
}
