/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */

export type HeadingConfigNodeSize =
	(typeof HeadingConfigNodeSize)[keyof typeof HeadingConfigNodeSize];

export const HeadingConfigNodeSize = {
	sm: "sm",
	md: "md",
	lg: "lg",
} as const;
