/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */

export type HeadingConfigNodeType =
	(typeof HeadingConfigNodeType)[keyof typeof HeadingConfigNodeType];

export const HeadingConfigNodeType = {
	heading: "heading",
} as const;
