/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { HeadingConfigNodeSize } from "./headingConfigNodeSize";
import type { HeadingConfigNodeType } from "./headingConfigNodeType";

export interface HeadingConfigNode {
	type: HeadingConfigNodeType;
	size: HeadingConfigNodeSize;
	content: string;
}
