/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { IdentifierDependency } from "./identifierDependency";

export interface Identifier {
	pluginId: string;
	identifierId: string;
	dependencies: IdentifierDependency[];
	softDependencies: IdentifierDependency[];
}
