/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */

export type IntegerAttributeType =
	(typeof IntegerAttributeType)[keyof typeof IntegerAttributeType];

export const IntegerAttributeType = {
	integer: "integer",
} as const;
