/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { LanguageMapKeys } from "./languageMapKeys";

export interface LanguageMap {
	id: string;
	keys: LanguageMapKeys;
}
