/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */

export interface LibrarySearchDto {
	/**
	 * @minimum 1
	 * @maximum 30
	 */
	pageSize: number;
	/** @minimum 1 */
	page: number;
}
