/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { HeadingConfigNode } from "./headingConfigNode";
import type { SectionConfigNode } from "./sectionConfigNode";
import type { TextConfigNode } from "./textConfigNode";

export interface PluginConfig {
	node: TextConfigNode | HeadingConfigNode | SectionConfigNode;
}
