/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { PluginConfigStub } from "./pluginConfigStub";

export interface PluginConfigs {
	configs: PluginConfigStub[];
}
