/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { HeadingConfigNode } from "./headingConfigNode";
import type { SectionConfigNodeType } from "./sectionConfigNodeType";
import type { TextConfigNode } from "./textConfigNode";

export interface SectionConfigNode {
	type: SectionConfigNodeType;
	children: (TextConfigNode | HeadingConfigNode | SectionConfigNode)[];
}
