/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */

export type StringAttributeType =
	(typeof StringAttributeType)[keyof typeof StringAttributeType];

export const StringAttributeType = {
	string: "string",
} as const;
