/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { TaskStatus } from "./taskStatus";

export interface Task {
	uuid: string;
	/** @nullable */
	pluginId: string | null;
	taskId: string;
	status: TaskStatus;
	/**
	 * @minimum 0
	 * @maximum 100
	 * @nullable
	 */
	percent: number | null;
	resumable: boolean;
}
