/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */

export type TextConfigNodeType =
	(typeof TextConfigNodeType)[keyof typeof TextConfigNodeType];

export const TextConfigNodeType = {
	text: "text",
} as const;
