/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { Artist } from "./artist";

export interface TrackArtist {
	artistUuid: string;
	artist: Artist;
	/** @nullable */
	joinPhrase: string | null;
}
