/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Pipe Bomb API
 * OpenAPI spec version: 0.0.1
 */
import type { AttributeMap } from "./attributeMap";
import type { Identity } from "./identity";
import type { TrackArtist } from "./trackArtist";

export interface Track {
	id: string;
	pluginId: string;
	libraryId: string;
	title: string;
	/** @nullable */
	artists: TrackArtist[] | null;
	attributes: AttributeMap | null;
	/** @nullable */
	identities: Identity[] | null;
}
